import type { CourseAnomaly } from "./buildCourses";
import type { MasterIconSuggestion } from "./buildMasters";
import type { RequirementsResult } from "./parseRequirements";

export interface ReportInput {
  programCode: string;
  planId: number;
  year: number;
  courseCount: number;
  masterIds: string[];
  droppedSpecializations: { id: string; name: string }[];
  requirements: RequirementsResult;
  anomalies: CourseAnomaly[];
  iconSuggestions: MasterIconSuggestion[];
  /** Requirement course codes that are not in this plan's course list. */
  danglingCourses: { master: string; codes: string[] }[];
  mastersWithoutCourses: string[];
}

const fence = (value: unknown) => `\`${JSON.stringify(value)}\``;

export function renderReport(input: ReportInput): string {
  const lines: string[] = [];
  const { requirements, traces: allTraces, unmatched } = input.requirements;

  lines.push(`# ${input.programCode} ${input.year} (plan ${input.planId}) - requirements review`);
  lines.push("");
  lines.push(
    "Generated by `scripts/scrape-liu.ts`. Review this before running `npm run seed`: the profile",
    "rules on studieinfo are free prose, so everything below is a best-effort reading of them.",
  );
  lines.push("");
  lines.push(
    `- Courses: **${input.courseCount}**`,
    `- Masters: **${input.masterIds.length}** (${input.masterIds.join(", ") || "none"})`,
  );
  if (input.droppedSpecializations.length > 0) {
    lines.push(
      `- Dropped specialisations (technical orientations and language tracks, not master profiles): ${input.droppedSpecializations
        .map((s) => `${s.id} (${s.name})`)
        .join(", ")}`,
    );
  }
  lines.push("");

  // The same rule sentence can appear in several sections of the plan prose.
  const seenTraces = new Set<string>();
  const traces = allTraces.filter((t) => {
    const key = `${t.master}|${JSON.stringify(t.requirement)}|${t.source}`;
    if (seenTraces.has(key)) return false;
    seenTraces.add(key);
    return true;
  });

  const approximations = traces.filter((t) => t.approximation);
  lines.push("## Approximations");
  lines.push("");
  if (approximations.length === 0) {
    lines.push("_None - every rule mapped cleanly onto an existing requirement type._");
  } else {
    lines.push(
      "These rules have no exact representation in the 7 supported requirement types.",
      "The emitted requirement is weaker than the real rule.",
      "",
    );
    for (const trace of approximations) {
      lines.push(`- **${trace.master}** ${trace.requirement ? fence(trace.requirement) : "(dropped)"}`);
      lines.push(`  - why: ${trace.approximation}`);
      lines.push(`  - source: _${trace.source}_`);
    }
  }
  lines.push("");

  lines.push("## Unparsed rule text");
  lines.push("");
  if (unmatched.length === 0) {
    lines.push("_Every sentence in the rules section matched a known pattern._");
  } else {
    lines.push(
      "Sentences in the profile-rules section that matched no pattern. These are the gaps -",
      "if any of them is a real requirement, add it to the JSON by hand.",
      "",
    );
    for (const item of unmatched) {
      lines.push(`- **${item.master}**: ${item.sentence}`);
    }
  }
  lines.push("");

  lines.push("## Anomalies");
  lines.push("");
  const anomalyLines: string[] = [];
  for (const a of input.anomalies) anomalyLines.push(`- \`${a.courseCode}\`: ${a.note}`);
  for (const d of input.danglingCourses) {
    anomalyLines.push(
      `- **${d.master}**: requirement references courses absent from this plan: ${d.codes.join(", ")} (the seed will log "No courses found for requirement")`,
    );
  }
  for (const m of input.mastersWithoutCourses) {
    anomalyLines.push(`- **${m}**: no courses are attributed to this master in the plan`);
  }
  for (const s of input.iconSuggestions) {
    anomalyLines.push(
      `- **${s.masterId}** (${s.name}): wanted icon \`${s.suggested}\`, which is not in \`lib/iconRegistry.ts\`; used \`${s.usedInstead}\``,
    );
  }
  lines.push(anomalyLines.length > 0 ? anomalyLines.join("\n") : "_None._");
  lines.push("");

  lines.push("## Every emitted requirement and its source");
  lines.push("");
  for (const master of Object.keys(requirements)) {
    lines.push(`### ${master}`);
    lines.push("");
    const masterTraces = traces.filter((t) => t.master === master && t.requirement);
    if (masterTraces.length === 0) {
      lines.push("_No requirements._");
    } else {
      for (const trace of masterTraces) {
        lines.push(`- ${fence(trace.requirement)}`);
        lines.push(`  - from: ${trace.source || "_(structural, from the plan tables)_"}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}
